export const NOELLE = 10000034;

export const FIGHT_PROP_NAMES = {
  FIGHT_PROP_MAX_HP: 'HP',
  FIGHT_PROP_HP_PERCENT: 'PHP',
  FIGHT_PROP_ATTACK: 'ATK',
  FIGHT_PROP_ATTACK_PERCENT: 'PATK',
  FIGHT_PROP_DEFENSE: 'DEF',
  FIGHT_PROP_DEFENSE_PERCENT: 'PDEF',
  FIGHT_PROP_ELEMENT_MASTERY: 'EM',
  FIGHT_PROP_CRITICAL: 'CR',
  FIGHT_PROP_CRITICAL_HURT: 'CD',
  FIGHT_PROP_CHARGE_EFFICIENCY: 'ER',
  FIGHT_PROP_FIRE_ADD_HURT: 'PyroDMG',
  FIGHT_PROP_WATER_ADD_HURT: 'HydroDMG',
  FIGHT_PROP_GRASS_ADD_HURT: 'DendroDMG',
  FIGHT_PROP_ELEC_ADD_HURT: 'ElectroDMG',
  FIGHT_PROP_WIND_ADD_HURT: 'AnemoDMG',
  FIGHT_PROP_ICE_ADD_HURT: 'CryoDMG',
  FIGHT_PROP_ROCK_ADD_HURT: 'GeoDMG',
  FIGHT_PROP_PHYSICAL_ADD_HURT: 'PhysDMG',
}

export const PERCENT_PROPS = [
  'PHP',
  'PATK',
  'PDEF',
  'CR',
  'CD',
  'ER',
  'PyroDMG',
  'HydroDMG',
  'DendroDMG',
  'ElectroDMG',
  'AnemoDMG',
  'CryoDMG',
  'GeoDMG',
  'PhysDMG',
];

export const NAMELESS = {
  lvl: 90,
  stats: {
    res: 0.1,
  },
}